name: VoiceCloning
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python==3.10
  - pip
  - numpy
  - pytorch==2.0.0
  - torchvision==0.15.0
  - torchaudio==2.0.0
  - cudatoolkit=11.8
  - python-dotenv
  - libsndfile
  - ffmpeg
  - pip:
    - pydub
    - assemblyai
    - git+https://github.com/m-bain/whisperx.git
    - spleeter
    - git+https://github.com/facebookresearch/demucs#egg=demucs
    - git+https://github.com/coqui-ai/TTS#egg=tts[all,dev,notebooks]